apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "app-scanner"
  namespace: "scanner"
  labels:
    app: "frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "frontend"
  template:
    metadata:
      labels:
        app: "frontend"
    spec:
      containers:
        - name: "app-scanner"
          image: "232679411998.dkr.ecr.us-east-1.amazonaws.com/k8s-project:xyz"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"